# Copyright 2020 the .NET Foundation
# Licensed under the MIT License

trigger:
  branches:
    include:
      - master

parameters:
- name: 'zolaVersion'
  default: '0.10.1'
  type: string

jobs:
- job: Main
  pool:
    vmImage: windows-latest

  steps:

  # Setup

  - checkout: self
    submodules: recursive

  - task: NodeTool@0
    displayName: Set up node.js
    inputs:
      versionSpec: '>=12'

  - script: npm cache clean -f
    displayName: npm cache clean

  # On `master`, we immediately perform the merge with `beta` that assigns
  # version numbers.

  - script: |
      git config --global user.email "wwt@aas.org"
      git config --global user.name "wwt-pipelines-bot"
      git tag temp-checkout-head HEAD
      git switch beta
      git merge --no-ff -m "Merge update to beta" temp-checkout-head
      git tag -d temp-checkout-HEAD
      npx lerna version --yes --amend --no-push --conventional-commits --conventional-prerelease
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Merge into beta branch

  # ScriptSharp build

  - task: MSBuild@1
    displayName: Build WebGL Engine with ScriptSharp
    inputs:
      solution: 'engine/WebGlEngine.sln'
      msbuildVersion: '16.0'
      msbuildArchitecture: 'x64'
      clean: true

  - task: CopyFiles@2
    displayName: Stage ScriptSharp artifacts
    inputs:
      sourceFolder: '.'
      contents: |
        engine/wwtlib/bin/wwtlib.js
      targetFolder: $(Build.ArtifactStagingDirectory)
      cleanTargetFolder: true

  - task: PublishPipelineArtifact@0
    displayName: Publish ScriptSharp artifacts
    inputs:
      artifactName: scriptsharp
      targetPath: $(Build.ArtifactStagingDirectory)/engine/wwtlib

  # JavaScript/TypeScript build process can begin in earnest

  - script: npx lerna bootstrap --concurrency=1
    displayName: Lerna NPM setup

  - script: npm run build
    displayName: NPM build

  - script: |
      mkdir $(Build.ArtifactStagingDirectory)\engine-hosted
      cp engine\wwtlib\bin\wwtlib.js $(Build.ArtifactStagingDirectory)\engine-hosted\wwtlib.js
      cp engine\src\index.js $(Build.ArtifactStagingDirectory)\engine-hosted\wwtsdk.js
      cp engine\src\index.min.js $(Build.ArtifactStagingDirectory)\engine-hosted\wwtsdk.min.js
      cp engine\src\index.d.ts $(Build.ArtifactStagingDirectory)\engine-hosted\wwtsdk.d.ts
    displayName: Stage JavaScript hosted artifacts

  - task: PublishPipelineArtifact@0
    displayName: Publish JavaScript hosted artifacts
    inputs:
      artifactName: engine-hosted
      targetPath: $(Build.ArtifactStagingDirectory)/engine-hosted

  - script: npm run lint
    displayName: NPM lint

  - script: npm run test
    displayName: NPM test

  - task: PublishTestResults@2
    displayName: Publish test results
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'engine/tests/results.xml'

  # TEMP TESTING POSTPUBLISH IDEA

  - script: lerna run postpublish
    displayName: TEMP FORCE POSTPUBLISH

  - bash: |
      echo pub astro $publishedAstroVersion qqq
    displayName: TEMP TEST1 POSTPUB

  - script: running it
    condition: and(succeeded(), ne(variables['publishedAstroVersion'], ''))
    displayName: TEMP TEST2 POSTPUB

  - script: running this thing
    condition: and(succeeded(), ne(variables['publishedSomeOtherVersion'], ''))
    displayName: TEMP TEST3 POSTPUB

  # Docs

  - script: npm run doc
    displayName: NPM doc

  - powershell: |
      $u = 'https://github.com/getzola/zola/releases/download/v${{ parameters.zolaVersion }}/zola-v${{ parameters.zolaVersion }}-x86_64-pc-windows-msvc.zip'
      Invoke-WebRequest -Uri $u -OutFile zola.zip

      Add-Type -assembly "System.IO.Compression.Filesystem";
      [IO.Compression.Zipfile]::ExtractToDirectory("zola.zip", ".");
    displayName: Install Zola

  # The check is failing spuriously on Azure Pipelines too often right now (2020 Apr).
  # - powershell: |
  #     cd docs
  #     ..\zola.exe check
  #   displayName: Check Zola docs site

  - powershell: |
      cd docs
      ..\zola.exe build -o $(Build.ArtifactStagingDirectory)/docs
    displayName: Zola docs build

  - task: PublishPipelineArtifact@0
    displayName: Publish docs artifacts
    inputs:
      artifactName: docs
      targetPath: $(Build.ArtifactStagingDirectory)/docs

  # Release processes. If we've made it this far on `master`, we should publish our beta
  # releases and update the `latest` forms of the web assets.

  - powershell: |
      $branch = "$(Build.SourceBranch)"
      if ($branch -eq "refs/heads/master") {
        Write-Host "##vso[task.setvariable variable=docsVersionText;]latest"
        Write-Host "##vso[task.setvariable variable=engineVersionText;]latest"
      }
    displayName: Set release version text variables

  - script: |
      git -c "credential.helper=!f() { echo username=token; echo password=%GITHUB_TOKEN%; };f" push --tags origin beta:beta
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Update beta branch
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)

  # I can only get this step to work using bash. No error message when running in cmd.
  - bash: |
      npm config set "//registry.npmjs.org/:_authToken=$NPM_TOKEN"
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Set up NPM auth
    failOnStderr: false
    env:
      NPM_TOKEN: $(NPM_TOKEN)

  - script: |
      npx lerna publish --yes --dist-tag=beta from-package
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Publish new beta packages to NPM

  ### - task: AzureFileCopy@3
  ###   displayName: Release hosted engine artifacts
  ###   inputs:
  ###     SourcePath: '$(build.artifactStagingDirectory)/engine-hosted'
  ###     azureSubscription: 'aas@wwtadmindotnetfoundation'
  ###     Destination: 'AzureBlob'
  ###     storage: 'wwtwebstatic'
  ###     ContainerName: '$web'
  ###     blobPrefix: engine/$(engineVersionText)

  ### - task: AzureFileCopy@3
  ###   displayName: Release documentation
  ###   inputs:
  ###     SourcePath: '$(build.artifactStagingDirectory)/docs'
  ###     azureSubscription: 'aas@wwtadmindotnetfoundation'
  ###     Destination: 'AzureBlob'
  ###     storage: 'wwtwebstatic'
  ###     ContainerName: '$web'
  ###     blobPrefix: '_docs/webgl-reference/$(docsVersionText)'

  # CDN purges - last since they are slow and close to optional

  ### - task: AzurePowerShell@4
  ###   displayName: CDN purge - hosted engine artifacts
  ###   inputs:
  ###     azureSubscription: 'aas@wwtadmindotnetfoundation'
  ###     azurePowerShellVersion: 'LatestVersion'
  ###     scriptType: 'inlineScript'
  ###     inline: |
  ###       Unpublish-AzCdnEndpointContent `
  ###         -ProfileName wwt-cdn-01 `
  ###         -ResourceGroupName wwt-web01 `
  ###         -EndpointName wwtweb-prod `
  ###         -PurgeContent '/engine/$(engineVersionText)/*'

  ### - task: AzurePowerShell@4
  ###   displayName: CDN purge - docs
  ###   inputs:
  ###     azureSubscription: 'aas@wwtadmindotnetfoundation'
  ###     azurePowerShellVersion: 'LatestVersion'
  ###     scriptType: 'inlineScript'
  ###     inline: |
  ###       Unpublish-AzCdnEndpointContent `
  ###         -ProfileName wwt-cdn-01 `
  ###         -ResourceGroupName wwt-web01 `
  ###         -EndpointName wwtwebdocs-prod `
  ###         -PurgeContent '/webgl-reference/$(docsVersionText)/*'
