# Copyright 2020 the .NET Foundation
# Licensed under the MIT License

trigger:
  branches:
    include:
      - master
      - release

parameters:
- name: 'zolaVersion'
  default: '0.10.1'
  type: string

jobs:
- job: Main
  pool:
    vmImage: windows-latest

  steps:

  # Setup

  - checkout: self
    submodules: recursive

  - task: NodeTool@0
    displayName: Set up node.js
    inputs:
      versionSpec: '>=12'

  - script: npm cache clean -f
    displayName: npm cache clean

  # On `master` or pull requests thereto, we immediately create the merge commit
  # that would update the `release` branch with version bumps from the new changes.

  - script: |
      git config --global user.email "wwt@aas.org"
      git config --global user.name "wwt-pipelines-bot"
      git tag temp-checkout-head HEAD
      git switch release
      git merge --no-ff -m "Automated prereleases from latest master" temp-checkout-head
      git tag -d temp-checkout-head
      npx lerna version --yes --amend --no-push --no-changelog --conventional-commits --conventional-prerelease --preid=beta
    condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['System.PullRequest.TargetBranch'], 'master')))
    displayName: Create merged release branch

  # ScriptSharp build

  - task: MSBuild@1
    displayName: Build WebGL Engine with ScriptSharp
    inputs:
      solution: 'engine/WebGlEngine.sln'
      msbuildVersion: '16.0'
      msbuildArchitecture: 'x64'
      clean: true

  - task: CopyFiles@2
    displayName: Stage ScriptSharp artifacts
    inputs:
      sourceFolder: '.'
      contents: |
        engine/wwtlib/bin/wwtlib.js
      targetFolder: $(Build.ArtifactStagingDirectory)
      cleanTargetFolder: true

  - task: PublishPipelineArtifact@0
    displayName: Publish ScriptSharp artifacts
    inputs:
      artifactName: scriptsharp
      targetPath: $(Build.ArtifactStagingDirectory)/engine/wwtlib

  # JavaScript/TypeScript build process can begin in earnest

  - script: npx lerna bootstrap --concurrency=1
    displayName: Lerna NPM setup

  - script: npm run build
    displayName: NPM build

  - script: |
      mkdir $(Build.ArtifactStagingDirectory)\engine-hosted
      cp engine\wwtlib\bin\wwtlib.js $(Build.ArtifactStagingDirectory)\engine-hosted\wwtlib.js
      cp engine\src\index.js $(Build.ArtifactStagingDirectory)\engine-hosted\wwtsdk.js
      cp engine\src\index.min.js $(Build.ArtifactStagingDirectory)\engine-hosted\wwtsdk.min.js
      cp engine\src\index.d.ts $(Build.ArtifactStagingDirectory)\engine-hosted\wwtsdk.d.ts
    displayName: Stage JavaScript hosted artifacts

  - task: PublishPipelineArtifact@0
    displayName: Publish JavaScript hosted artifacts
    inputs:
      artifactName: engine-hosted
      targetPath: $(Build.ArtifactStagingDirectory)/engine-hosted

  - task: CopyFiles@2
    displayName: Stage embed app artifacts
    inputs:
      sourceFolder: embed/dist
      targetFolder: $(Build.ArtifactStagingDirectory)/embed

  - task: PublishPipelineArtifact@0
    displayName: Publish embed app artifacts
    inputs:
      artifactName: embed
      targetPath: $(Build.ArtifactStagingDirectory)/embed

  - script: npm run lint
    displayName: NPM lint

  - script: npm run test
    displayName: NPM test

  - task: PublishTestResults@2
    displayName: Publish test results
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: 'engine/tests/results.xml'

  # Docs

  - script: npm run doc
    displayName: NPM doc

  - powershell: |
      $u = 'https://github.com/getzola/zola/releases/download/v${{ parameters.zolaVersion }}/zola-v${{ parameters.zolaVersion }}-x86_64-pc-windows-msvc.zip'
      Invoke-WebRequest -Uri $u -OutFile zola.zip

      Add-Type -assembly "System.IO.Compression.Filesystem";
      [IO.Compression.Zipfile]::ExtractToDirectory("zola.zip", ".");
    displayName: Install Zola

  # The check is failing spuriously on Azure Pipelines too often right now (2020 Apr).
  # - powershell: |
  #     cd docs
  #     ..\zola.exe check
  #   displayName: Check Zola docs site

  - powershell: |
      cd docs
      ..\zola.exe build -o $(Build.ArtifactStagingDirectory)/docs
    displayName: Zola docs build

  - task: PublishPipelineArtifact@0
    displayName: Publish docs artifacts
    inputs:
      artifactName: docs
      targetPath: $(Build.ArtifactStagingDirectory)/docs

  # On `master`, now let's update the `release` branch with our new versions.
  # This will trigger a CI run there that will actually execute the releases
  # and deployments.

  - script: |
      git -c "credential.helper=!f() { echo username=token; echo password=%GITHUB_TOKEN%; };f" push --tags origin release:release
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    displayName: Update release branch (master only)
    env:
      GITHUB_TOKEN: $(GITHUB_TOKEN)

  # Release processes.
  #
  # First, publishing NPM packages.I can only get this step to work using bash.
  # No error message when running in cmd.

  - bash: |
      npm config set "//registry.npmjs.org/:_authToken=$NPM_TOKEN"
    displayName: Set up NPM auth
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/release'))
    failOnStderr: false
    env:
      NPM_TOKEN: $(NPM_TOKEN)

  - script: |
      npx lerna publish --yes --pre-dist-tag=beta from-package
    displayName: Publish new packages to NPM
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/release'))
    env:
      NPM_TOKEN: $(NPM_TOKEN)

  # Time for additional deployment steps, beyond any NPM publishing.
  #
  # Some of the packages have "postpublish" stages that will have been run by
  # lerna if a new version of the package was indeed published. These stages use
  # the ##vso syntax to set variables that we can then use to orchestrate other
  # aspects of the continuous deployment pipeline.
  #
  # Since the docs combine outputs from nearly every submodule, we deploy new
  # versions on every update of `release`. Because the docs combine many
  # different submodules, that raises the question of what version number to
  # assign. As a heuristic, we track @wwtelescope/engine. If a new non-prelease
  # version of the engine is published, we deploy the docs in a versioned
  # directory; otherwise we deploy under `latest`.

  - powershell: |
      $engineVers = "$(publishedEngineVersion)"
      Write-Host "##vso[task.setvariable variable=maybePublishedEngineVersion;]$engineVers"

      if ($engineVers.IndexOf("-beta") -ne -1) {
        Write-Host "##vso[task.setvariable variable=engineVersionText;]latest"
      } else {
        $majmin = ($engineVers -Split '\.')[0..1] -Join '.'
        Write-Host "##vso[task.setvariable variable=engineVersionText;]$majmin"
      }
    condition: and(succeeded(), ne(variables['publishedEngineVersion'], ''))
    displayName: Set @wwtelescope/engine deployment variables

  # An awkward hack for convenient setup of the docs deployment variables.
  - powershell: |
      Write-Host "##vso[task.setvariable variable=maybePublishedEngineVersion;]nochange-beta"
    condition: and(succeeded(), eq(variables['publishedEngineVersion'], ''))
    displayName: Default @wwtelescope/engine deployment variables

  - powershell: |
      $embedVers = "$(publishedEmbedVersion)"

      if ($embedVers.IndexOf("-beta") -ne -1) {
        Write-Host "##vso[task.setvariable variable=embedVersionText;]latest"
      } else {
        $major = ($embedVers -Split '\.')[0]
        Write-Host "##vso[task.setvariable variable=embedVersionText;]$major"
      }
    condition: and(succeeded(), ne(variables['publishedEmbedVersion'], ''))
    displayName: Set @wwtelescope/embed deployment variables

  - powershell: |
      $engineVers = "$(maybePublishedEngineVersion)"
      if ($engineVers.IndexOf("-beta") -ne -1) {
        Write-Host "##vso[task.setvariable variable=docsVersionText;]latest"
      } else {
        $majmin = ($engineVers -Split '\.')[0..1] -Join '.'
        Write-Host "##vso[task.setvariable variable=docsVersionText;]$majmin"
      }
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/release'))
    displayName: Set docs deployment variables

  - task: AzureFileCopy@3
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/release'), ne(variables['publishedEngineVersion'], ''))
    displayName: Deploy hosted engine artifacts
    inputs:
      SourcePath: '$(build.artifactStagingDirectory)/engine-hosted'
      azureSubscription: 'aas@wwtadmindotnetfoundation'
      Destination: 'AzureBlob'
      storage: 'wwtwebstatic'
      ContainerName: '$web'
      blobPrefix: engine/$(engineVersionText)

  - task: AzureFileCopy@3
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/release'), ne(variables['publishedEmbedVersion'], ''))
    displayName: Deploy embed web application
    inputs:
      SourcePath: '$(build.artifactStagingDirectory)/embed'
      azureSubscription: 'aas@wwtadmindotnetfoundation'
      Destination: 'AzureBlob'
      storage: 'wwtwebstatic'
      ContainerName: '$web'
      blobPrefix: embed/$(embedVersionText)/wwt

  - task: AzureFileCopy@3
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/release'))
    displayName: Deploy documentation
    inputs:
      SourcePath: '$(build.artifactStagingDirectory)/docs'
      azureSubscription: 'aas@wwtadmindotnetfoundation'
      Destination: 'AzureBlob'
      storage: 'wwtwebstatic'
      ContainerName: '$web'
      blobPrefix: '_docs/webgl-reference/$(docsVersionText)'

  # CDN purges - last since they are slow and close to optional

  - task: AzurePowerShell@4
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/release'), ne(variables['publishedEngineVersion'], ''))
    displayName: CDN purge - hosted engine artifacts
    inputs:
      azureSubscription: 'aas@wwtadmindotnetfoundation'
      azurePowerShellVersion: 'LatestVersion'
      scriptType: 'inlineScript'
      inline: |
        Unpublish-AzCdnEndpointContent `
          -ProfileName wwt-cdn-01 `
          -ResourceGroupName wwt-web01 `
          -EndpointName wwtweb-prod `
          -PurgeContent '/engine/$(engineVersionText)/*'

  - task: AzurePowerShell@4
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/release'), ne(variables['publishedEmbedVersion'], ''))
    displayName: CDN purge - embed web app
    inputs:
      azureSubscription: 'aas@wwtadmindotnetfoundation'
      azurePowerShellVersion: 'LatestVersion'
      scriptType: 'inlineScript'
      inline: |
        Unpublish-AzCdnEndpointContent `
          -ProfileName wwt-cdn-01 `
          -ResourceGroupName wwt-web01 `
          -EndpointName wwtweb-prod `
          -PurgeContent '/embed/$(embedVersionText)/wwt/*'

  - task: AzurePowerShell@4
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/release'))
    displayName: CDN purge - docs
    inputs:
      azureSubscription: 'aas@wwtadmindotnetfoundation'
      azurePowerShellVersion: 'LatestVersion'
      scriptType: 'inlineScript'
      inline: |
        Unpublish-AzCdnEndpointContent `
          -ProfileName wwt-cdn-01 `
          -ResourceGroupName wwt-web01 `
          -EndpointName wwtwebdocs-prod `
          -PurgeContent '/webgl-reference/$(docsVersionText)/*'
