# Copyright 2020 the .NET Foundation
# Licensed under the MIT License

trigger:
  branches:
    include:
    - cranko
    - rc

stages:
- stage: ScriptSharpBuild
  jobs:
  - template: azure-scriptsharp-build.yml

- stage: MainBuild
  jobs:
  - template: azure-main-build.yml

- stage: Deploy
  condition: and(succeeded('BuildAndTest'), ne(variables['build.reason'], 'PullRequest'))
  jobs:
    - template: azure-deployment.yml
      parameters:
        isMainDev: ${{ ne(variables['Build.SourceBranchName'], 'rc') }}
        isRelease: ${{ eq(variables['Build.SourceBranchName'], 'rc') }}
